name: Build

on:
  schedule:
    - cron: "0 1 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: git commit
        run: |-
          git config --global user.name "acc-is-sponge"
          git config --global user.email "acc.is.sponge@gmail.com"
          git add latest-regulations.json scoresaber
          git commit -m "Update Regulations"
          git push
